[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--disable-new-dtags", "-C", "link-arg=-Wl,-rpath,$ORIGIN/../share/com.lmaxyz.SlintAuroraDemo/lib", "-C", "link-arg=-L/usr/share/com.lmaxyz.SlintAuroraDemo/lib"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "link-arg=-Wl,--disable-new-dtags", "-C", "link-arg=-Wl,-rpath,$ORIGIN/../share/com.lmaxyz.SlintAuroraDemo/lib", "-C", "link-arg=-L/usr/share/com.lmaxyz.SlintAuroraDemo/lib"]
